# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snacam < Formula
  desc "Convert Strings to Specified Case"
  homepage "https://github.com/kohbis/snacam"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kohbis/snacam/releases/download/v0.0.1/snacam_0.0.1_Darwin_arm64.tar.gz"
      sha256 "f1ecd42facc39686dde5b5c9e2ecb782b1b163ea6ffa12fa33f5059c4b669fdf"

      def install
        bin.install "snacam"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kohbis/snacam/releases/download/v0.0.1/snacam_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "0c730fa035bd204aa7d3f40c59e31de8e96220c0914f3fc65af6fe1b7d166cdc"

      def install
        bin.install "snacam"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kohbis/snacam/releases/download/v0.0.1/snacam_0.0.1_Linux_arm64.tar.gz"
      sha256 "ce659793ca0070453f44024904c3f27fe0aafe41294c183e1c8d2d4690b92738"

      def install
        bin.install "snacam"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kohbis/snacam/releases/download/v0.0.1/snacam_0.0.1_Linux_x86_64.tar.gz"
      sha256 "da8068c011e601216aec3388e52ddda92aa91d9661d799aea43ba3c863491bd6"

      def install
        bin.install "snacam"
      end
    end
  end
end
