# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snacam < Formula
  desc "Convert Strings to Specified Case"
  homepage "https://github.com/kohbis/snacam"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kohbis/snacam/releases/download/v0.1.1/snacam_0.1.1_Darwin_arm64.tar.gz"
      sha256 "db56407f480864b687211379635d5900ddd4cd8f6065e960ffcce151e3dfb868"

      def install
        bin.install "snacam"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kohbis/snacam/releases/download/v0.1.1/snacam_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "7d82332651c583116dcd682d0e43ddd081fe86d4cfe20e91ec12f8002e4fd588"

      def install
        bin.install "snacam"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kohbis/snacam/releases/download/v0.1.1/snacam_0.1.1_Linux_arm64.tar.gz"
      sha256 "4adb00f6b407ed8f37235cb3ea6ad9245ed0c8922e369409d62271129210b2af"

      def install
        bin.install "snacam"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kohbis/snacam/releases/download/v0.1.1/snacam_0.1.1_Linux_x86_64.tar.gz"
      sha256 "94963cf558c325690d942014b75a86a38c13bf29518e2dc0bef50044292434c9"

      def install
        bin.install "snacam"
      end
    end
  end
end
